// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.grpc.home.product;

public interface ModelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.home.product.ModelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  java.util.List<com.grpc.home.product.ModelResponse.ModelBase> 
      getModelBaseList();
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  com.grpc.home.product.ModelResponse.ModelBase getModelBase(int index);
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  int getModelBaseCount();
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  java.util.List<? extends com.grpc.home.product.ModelResponse.ModelBaseOrBuilder> 
      getModelBaseOrBuilderList();
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  com.grpc.home.product.ModelResponse.ModelBaseOrBuilder getModelBaseOrBuilder(
      int index);
}
