// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.grpc.home.product;

/**
 * Protobuf type {@code com.grpc.home.product.ModelResponse}
 */
public  final class ModelResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.home.product.ModelResponse)
    ModelResponseOrBuilder {
  // Use ModelResponse.newBuilder() to construct.
  private ModelResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelResponse() {
    modelBase_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ModelResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              modelBase_ = new java.util.ArrayList<com.grpc.home.product.ModelResponse.ModelBase>();
              mutable_bitField0_ |= 0x00000001;
            }
            modelBase_.add(
                input.readMessage(com.grpc.home.product.ModelResponse.ModelBase.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        modelBase_ = java.util.Collections.unmodifiableList(modelBase_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.home.product.ModelResponse.class, com.grpc.home.product.ModelResponse.Builder.class);
  }

  public interface ModelBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.home.product.ModelResponse.ModelBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string price = 3;</code>
     */
    java.lang.String getPrice();
    /**
     * <code>string price = 3;</code>
     */
    com.google.protobuf.ByteString
        getPriceBytes();

    /**
     * <code>int32 total = 4;</code>
     */
    int getTotal();

    /**
     * <code>string status = 5;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 5;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string category = 6;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>string category = 6;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();
  }
  /**
   * Protobuf type {@code com.grpc.home.product.ModelResponse.ModelBase}
   */
  public  static final class ModelBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.home.product.ModelResponse.ModelBase)
      ModelBaseOrBuilder {
    // Use ModelBase.newBuilder() to construct.
    private ModelBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ModelBase() {
      code_ = 0;
      name_ = "";
      price_ = "";
      total_ = 0;
      status_ = "";
      category_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ModelBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              price_ = s;
              break;
            }
            case 32: {

              total_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              category_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_ModelBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_ModelBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.home.product.ModelResponse.ModelBase.class, com.grpc.home.product.ModelResponse.ModelBase.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private volatile java.lang.Object price_;
    /**
     * <code>string price = 3;</code>
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <code>string price = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTAL_FIELD_NUMBER = 4;
    private int total_;
    /**
     * <code>int32 total = 4;</code>
     */
    public int getTotal() {
      return total_;
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 5;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 6;
    private volatile java.lang.Object category_;
    /**
     * <code>string category = 6;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <code>string category = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, price_);
      }
      if (total_ != 0) {
        output.writeInt32(4, total_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, status_);
      }
      if (!getCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, category_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, price_);
      }
      if (total_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, total_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, status_);
      }
      if (!getCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, category_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.home.product.ModelResponse.ModelBase)) {
        return super.equals(obj);
      }
      com.grpc.home.product.ModelResponse.ModelBase other = (com.grpc.home.product.ModelResponse.ModelBase) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getName()
          .equals(other.getName());
      result = result && getPrice()
          .equals(other.getPrice());
      result = result && (getTotal()
          == other.getTotal());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && getCategory()
          .equals(other.getCategory());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTotal();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.home.product.ModelResponse.ModelBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.home.product.ModelResponse.ModelBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.home.product.ModelResponse.ModelBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.home.product.ModelResponse.ModelBase)
        com.grpc.home.product.ModelResponse.ModelBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_ModelBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_ModelBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.home.product.ModelResponse.ModelBase.class, com.grpc.home.product.ModelResponse.ModelBase.Builder.class);
      }

      // Construct using com.grpc.home.product.ModelResponse.ModelBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        name_ = "";

        price_ = "";

        total_ = 0;

        status_ = "";

        category_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_ModelBase_descriptor;
      }

      public com.grpc.home.product.ModelResponse.ModelBase getDefaultInstanceForType() {
        return com.grpc.home.product.ModelResponse.ModelBase.getDefaultInstance();
      }

      public com.grpc.home.product.ModelResponse.ModelBase build() {
        com.grpc.home.product.ModelResponse.ModelBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.grpc.home.product.ModelResponse.ModelBase buildPartial() {
        com.grpc.home.product.ModelResponse.ModelBase result = new com.grpc.home.product.ModelResponse.ModelBase(this);
        result.code_ = code_;
        result.name_ = name_;
        result.price_ = price_;
        result.total_ = total_;
        result.status_ = status_;
        result.category_ = category_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.home.product.ModelResponse.ModelBase) {
          return mergeFrom((com.grpc.home.product.ModelResponse.ModelBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.home.product.ModelResponse.ModelBase other) {
        if (other == com.grpc.home.product.ModelResponse.ModelBase.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          onChanged();
        }
        if (other.getTotal() != 0) {
          setTotal(other.getTotal());
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.home.product.ModelResponse.ModelBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.home.product.ModelResponse.ModelBase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <code>string price = 3;</code>
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string price = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string price = 3;</code>
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string price = 3;</code>
       */
      public Builder clearPrice() {
        
        price_ = getDefaultInstance().getPrice();
        onChanged();
        return this;
      }
      /**
       * <code>string price = 3;</code>
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        price_ = value;
        onChanged();
        return this;
      }

      private int total_ ;
      /**
       * <code>int32 total = 4;</code>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <code>int32 total = 4;</code>
       */
      public Builder setTotal(int value) {
        
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total = 4;</code>
       */
      public Builder clearTotal() {
        
        total_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 5;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 5;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 5;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 5;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>string category = 6;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string category = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string category = 6;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string category = 6;</code>
       */
      public Builder clearCategory() {
        
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>string category = 6;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        category_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.home.product.ModelResponse.ModelBase)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.home.product.ModelResponse.ModelBase)
    private static final com.grpc.home.product.ModelResponse.ModelBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.home.product.ModelResponse.ModelBase();
    }

    public static com.grpc.home.product.ModelResponse.ModelBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ModelBase>
        PARSER = new com.google.protobuf.AbstractParser<ModelBase>() {
      public ModelBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ModelBase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ModelBase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ModelBase> getParserForType() {
      return PARSER;
    }

    public com.grpc.home.product.ModelResponse.ModelBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int MODELBASE_FIELD_NUMBER = 1;
  private java.util.List<com.grpc.home.product.ModelResponse.ModelBase> modelBase_;
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  public java.util.List<com.grpc.home.product.ModelResponse.ModelBase> getModelBaseList() {
    return modelBase_;
  }
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  public java.util.List<? extends com.grpc.home.product.ModelResponse.ModelBaseOrBuilder> 
      getModelBaseOrBuilderList() {
    return modelBase_;
  }
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  public int getModelBaseCount() {
    return modelBase_.size();
  }
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  public com.grpc.home.product.ModelResponse.ModelBase getModelBase(int index) {
    return modelBase_.get(index);
  }
  /**
   * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
   */
  public com.grpc.home.product.ModelResponse.ModelBaseOrBuilder getModelBaseOrBuilder(
      int index) {
    return modelBase_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < modelBase_.size(); i++) {
      output.writeMessage(1, modelBase_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < modelBase_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, modelBase_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.home.product.ModelResponse)) {
      return super.equals(obj);
    }
    com.grpc.home.product.ModelResponse other = (com.grpc.home.product.ModelResponse) obj;

    boolean result = true;
    result = result && getModelBaseList()
        .equals(other.getModelBaseList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getModelBaseCount() > 0) {
      hash = (37 * hash) + MODELBASE_FIELD_NUMBER;
      hash = (53 * hash) + getModelBaseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.home.product.ModelResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.home.product.ModelResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.home.product.ModelResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.home.product.ModelResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.home.product.ModelResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.home.product.ModelResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.home.product.ModelResponse)
      com.grpc.home.product.ModelResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.home.product.ModelResponse.class, com.grpc.home.product.ModelResponse.Builder.class);
    }

    // Construct using com.grpc.home.product.ModelResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getModelBaseFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (modelBaseBuilder_ == null) {
        modelBase_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        modelBaseBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.home.product.ProductServiceOuterClass.internal_static_com_grpc_home_product_ModelResponse_descriptor;
    }

    public com.grpc.home.product.ModelResponse getDefaultInstanceForType() {
      return com.grpc.home.product.ModelResponse.getDefaultInstance();
    }

    public com.grpc.home.product.ModelResponse build() {
      com.grpc.home.product.ModelResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.grpc.home.product.ModelResponse buildPartial() {
      com.grpc.home.product.ModelResponse result = new com.grpc.home.product.ModelResponse(this);
      int from_bitField0_ = bitField0_;
      if (modelBaseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          modelBase_ = java.util.Collections.unmodifiableList(modelBase_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.modelBase_ = modelBase_;
      } else {
        result.modelBase_ = modelBaseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.home.product.ModelResponse) {
        return mergeFrom((com.grpc.home.product.ModelResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.home.product.ModelResponse other) {
      if (other == com.grpc.home.product.ModelResponse.getDefaultInstance()) return this;
      if (modelBaseBuilder_ == null) {
        if (!other.modelBase_.isEmpty()) {
          if (modelBase_.isEmpty()) {
            modelBase_ = other.modelBase_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureModelBaseIsMutable();
            modelBase_.addAll(other.modelBase_);
          }
          onChanged();
        }
      } else {
        if (!other.modelBase_.isEmpty()) {
          if (modelBaseBuilder_.isEmpty()) {
            modelBaseBuilder_.dispose();
            modelBaseBuilder_ = null;
            modelBase_ = other.modelBase_;
            bitField0_ = (bitField0_ & ~0x00000001);
            modelBaseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getModelBaseFieldBuilder() : null;
          } else {
            modelBaseBuilder_.addAllMessages(other.modelBase_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.home.product.ModelResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.home.product.ModelResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.grpc.home.product.ModelResponse.ModelBase> modelBase_ =
      java.util.Collections.emptyList();
    private void ensureModelBaseIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        modelBase_ = new java.util.ArrayList<com.grpc.home.product.ModelResponse.ModelBase>(modelBase_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.home.product.ModelResponse.ModelBase, com.grpc.home.product.ModelResponse.ModelBase.Builder, com.grpc.home.product.ModelResponse.ModelBaseOrBuilder> modelBaseBuilder_;

    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public java.util.List<com.grpc.home.product.ModelResponse.ModelBase> getModelBaseList() {
      if (modelBaseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(modelBase_);
      } else {
        return modelBaseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public int getModelBaseCount() {
      if (modelBaseBuilder_ == null) {
        return modelBase_.size();
      } else {
        return modelBaseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public com.grpc.home.product.ModelResponse.ModelBase getModelBase(int index) {
      if (modelBaseBuilder_ == null) {
        return modelBase_.get(index);
      } else {
        return modelBaseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder setModelBase(
        int index, com.grpc.home.product.ModelResponse.ModelBase value) {
      if (modelBaseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelBaseIsMutable();
        modelBase_.set(index, value);
        onChanged();
      } else {
        modelBaseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder setModelBase(
        int index, com.grpc.home.product.ModelResponse.ModelBase.Builder builderForValue) {
      if (modelBaseBuilder_ == null) {
        ensureModelBaseIsMutable();
        modelBase_.set(index, builderForValue.build());
        onChanged();
      } else {
        modelBaseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder addModelBase(com.grpc.home.product.ModelResponse.ModelBase value) {
      if (modelBaseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelBaseIsMutable();
        modelBase_.add(value);
        onChanged();
      } else {
        modelBaseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder addModelBase(
        int index, com.grpc.home.product.ModelResponse.ModelBase value) {
      if (modelBaseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelBaseIsMutable();
        modelBase_.add(index, value);
        onChanged();
      } else {
        modelBaseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder addModelBase(
        com.grpc.home.product.ModelResponse.ModelBase.Builder builderForValue) {
      if (modelBaseBuilder_ == null) {
        ensureModelBaseIsMutable();
        modelBase_.add(builderForValue.build());
        onChanged();
      } else {
        modelBaseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder addModelBase(
        int index, com.grpc.home.product.ModelResponse.ModelBase.Builder builderForValue) {
      if (modelBaseBuilder_ == null) {
        ensureModelBaseIsMutable();
        modelBase_.add(index, builderForValue.build());
        onChanged();
      } else {
        modelBaseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder addAllModelBase(
        java.lang.Iterable<? extends com.grpc.home.product.ModelResponse.ModelBase> values) {
      if (modelBaseBuilder_ == null) {
        ensureModelBaseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, modelBase_);
        onChanged();
      } else {
        modelBaseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder clearModelBase() {
      if (modelBaseBuilder_ == null) {
        modelBase_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        modelBaseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public Builder removeModelBase(int index) {
      if (modelBaseBuilder_ == null) {
        ensureModelBaseIsMutable();
        modelBase_.remove(index);
        onChanged();
      } else {
        modelBaseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public com.grpc.home.product.ModelResponse.ModelBase.Builder getModelBaseBuilder(
        int index) {
      return getModelBaseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public com.grpc.home.product.ModelResponse.ModelBaseOrBuilder getModelBaseOrBuilder(
        int index) {
      if (modelBaseBuilder_ == null) {
        return modelBase_.get(index);  } else {
        return modelBaseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public java.util.List<? extends com.grpc.home.product.ModelResponse.ModelBaseOrBuilder> 
         getModelBaseOrBuilderList() {
      if (modelBaseBuilder_ != null) {
        return modelBaseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(modelBase_);
      }
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public com.grpc.home.product.ModelResponse.ModelBase.Builder addModelBaseBuilder() {
      return getModelBaseFieldBuilder().addBuilder(
          com.grpc.home.product.ModelResponse.ModelBase.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public com.grpc.home.product.ModelResponse.ModelBase.Builder addModelBaseBuilder(
        int index) {
      return getModelBaseFieldBuilder().addBuilder(
          index, com.grpc.home.product.ModelResponse.ModelBase.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.home.product.ModelResponse.ModelBase modelBase = 1;</code>
     */
    public java.util.List<com.grpc.home.product.ModelResponse.ModelBase.Builder> 
         getModelBaseBuilderList() {
      return getModelBaseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.home.product.ModelResponse.ModelBase, com.grpc.home.product.ModelResponse.ModelBase.Builder, com.grpc.home.product.ModelResponse.ModelBaseOrBuilder> 
        getModelBaseFieldBuilder() {
      if (modelBaseBuilder_ == null) {
        modelBaseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.home.product.ModelResponse.ModelBase, com.grpc.home.product.ModelResponse.ModelBase.Builder, com.grpc.home.product.ModelResponse.ModelBaseOrBuilder>(
                modelBase_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        modelBase_ = null;
      }
      return modelBaseBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.home.product.ModelResponse)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.home.product.ModelResponse)
  private static final com.grpc.home.product.ModelResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.home.product.ModelResponse();
  }

  public static com.grpc.home.product.ModelResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelResponse>
      PARSER = new com.google.protobuf.AbstractParser<ModelResponse>() {
    public ModelResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModelResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModelResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelResponse> getParserForType() {
    return PARSER;
  }

  public com.grpc.home.product.ModelResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

