// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.grpc.home.product;

public interface emptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.home.product.emptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
