// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.grpc.home.product;

public interface ModelOneResponeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.home.product.ModelOneRespone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string price = 3;</code>
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 3;</code>
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>int32 total = 4;</code>
   */
  int getTotal();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string category = 6;</code>
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 6;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();
}
