// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.grpc.home.product;

public interface ModelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.home.product.ModelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();
}
